# Generated by Django 3.0.6 on 2020-05-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_desc',
            field=models.TextField(default='Yemek'),
        ),
        migrations.AddField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(default='../static/images/kebab.jpg', upload_to='../static/images/'),
        ),
    ]
