# Generated by Django 3.0.6 on 2020-05-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200517_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(default='kebab.jpg', upload_to='static/images/'),
        ),
    ]
