# Generated by Django 3.0.6 on 2020-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_auto_20200518_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(default='default.jpg', height_field=290, upload_to='food_pics', width_field=290),
        ),
    ]
