# Generated by Django 3.0.6 on 2020-05-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20200518_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(default='default.jpg', upload_to='food_pics'),
        ),
    ]
