# Generated by Django 3.0.6 on 2020-05-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_detail',
            field=models.TextField(null=True),
        ),
    ]
